repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
        exclude: \.ambr$
      - id: end-of-file-fixer
      - id: check-yaml
        args: ["--unsafe"]
      - id: check-toml

  - repo: https://github.com/sirosen/texthooks
    rev: 0.6.8
    hooks:
      - id: fix-smartquotes
      - id: fix-spaces

  - repo: local
    hooks:
      - id: hexagent
        name: format and lint hexagent
        language: system
        entry: make -C libs/hexagent format lint
        files: ^libs/hexagent/
        pass_filenames: false
